### ISSUE TITLE
config file not configure properly for sequanix

### ISSUE THREAD

**Issue by cokelaer** [sequana/rnaseq#18]
INFO:sequanix:Creating form based on config file
    'software_choice'
    <string>:19: (WARNING/2) Bullet list ends without a blank line; unexpected unindent.
    Traceback (most recent call last):
      File "/home/cokelaer/Work/github/forked/sequanix/sequanix/sequanix.py", line 749, in _update_sequana
        self.create_base_form()
     File "/home/cokelaer/Work/github/forked/sequanix/sequanix/sequanix.py", line 1141, in create_base_form
        rule_box = Ruleform(rule, contains, count, keywords, specials=specials)
      File "/home/cokelaer/Work/github/forked/sequanix/sequanix/widgets/widgets.py", line 108, in __init__
        option_widget = NumberOption(option, value)
      File "/home/cokelaer/Work/github/forked/sequanix/sequanix/widgets/widgets.py", line 281, in __init__
        self.number.setValue(value)
    OverflowError: argument 1 overflowed: value must be in the range -2147483648 to 2147483647
    Aborted (core dumped)

**Comment by cokelaer** [comment]
This is not a RNAseq pbl anymore but Qt with limited integer values.
